
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: nginx
    name: nginx
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - image: nginx
                  imagePullPolicy: Always
                  name: nginx
                  ports:
                    - containerPort: 80
                      protocol: TCP
                  resources: {}
                  volumeMounts:
                    - mountPath: /etc/nginx/nginx.conf
                      name: vol5673202223121082122
            restartPolicy: Always
            securityContext: {}
            volumes:
                - name: vol5673202223121082122
                  persistentVolumeClaim:
                    claimName: vol5673202223121082122
status: {}

...
