
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: chatbotui
    name: chatbotui
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - image: index.docker.io/myproject/chatbotui:latest
                  imagePullPolicy: Always
                  name: chatbot-ui
                  ports:
                    - containerPort: 3000
                      protocol: TCP
                  resources: {}
            restartPolicy: Always
            securityContext: {}
status: {}

...
