apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: mysql
  name: mysql
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: db
          image: index.docker.io/myproject/mysql:latest
          imagePullPolicy: Always
          name: db
          ports:
            - containerPort: 3306
              protocol: TCP
          resources: {}
      restartPolicy: Always
      securityContext: {}
status: {}
